version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "21:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: rc-trigger
    versions:
    - 5.2.0
    - 5.2.2
    - 5.2.3
    - 5.2.4
    - 5.2.5
  - dependency-name: rc-select
    versions:
    - 12.1.3
    - 12.1.5
    - 12.1.6
    - 12.1.7
    - 12.1.9
    - 9.2.3
  - dependency-name: rc-editor-core
    versions:
    - 0.8.8
